In [52]:
#numpy is a library that allows for the  use of array and matrices
import numpy as np

In [53]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [54]:
type(a)

numpy.ndarray

In [55]:
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [56]:
#creating a 2d array
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [57]:
#creating 3d array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [58]:
#creating an array with a specific data type 
print(a.dtype)

int64


In [59]:
#to get the no. of dimensions of an array 
print(a.ndim)

2


In [60]:
print(a.shape)

(2, 3)


In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [64]:
#randint generate random integer
np.random.randint(10,30, size=(3,3))

array([[28, 25, 22],
       [25, 23, 25],
       [26, 21, 12]], dtype=int32)

In [65]:
x = np.array([[7,2,3],[2,5,2],[3,5,1]])
y = np.array([[1,8,3],[3,7,2],[2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [66]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [67]:
#matrix multiplication
print(x@y)

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [68]:
#matrix multiplication
print(x.dot(y))

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [69]:
x.prod()

np.int64(12600)

In [70]:
x.mean()

np.float64(3.3333333333333335)

In [71]:
x.mean(axis=0) #mean of each column

array([4., 4., 2.])

In [72]:
x.mean(axis=1) #mean of each row

array([4., 3., 3.])

In [73]:
print(x.sum())
print(x.var()) # varient
print(x.std()) # standard deviation

30
3.3333333333333335
1.8257418583505538


In [74]:
z = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(z, 25)) #25th percentile
print(np.percentile(z, 50)) #50th percentile
print(np.percentile(z, 75)) #75th percentile 

3.0
5.0
7.0


In [75]:
arr = np.random.randint(10,50, size=(4,4))
print(arr)

[[38 30 46 24]
 [43 22 23 44]
 [17 17 14 14]
 [33 42 21 27]]


In [76]:
# to reshape
print('8*2')
print(arr.reshape(8,2))

8*2
[[38 30]
 [46 24]
 [43 22]
 [23 44]
 [17 17]
 [14 14]
 [33 42]
 [21 27]]


In [78]:
print('2*8')
print(arr.reshape(2,8))

2*8
[[38 30 46 24 43 22 23 44]
 [17 17 14 14 33 42 21 27]]


In [ ]:
print(x[0]) #first row
print(x[1]) # second row

[7 2 3]
[2 5 2]


In [ ]:
print(x[0,0]) #first row first element

7


In [ ]:
print(x[0,1]) #first row second element

2
